export const CATEGORY_GENRES = {
  Academic: [
    "Engineering",
    "Medical",
    "Law",
    "Business Studies",
    "Economics",
    "Mathematics",
    "Physics",
    "Chemistry",
    "Biology",
    "Computer Science",
  ],
  "Arts & Design": [
    "Graphic Design",
    "Fine Arts",
    "Illustration",
    "Photography",
    "Fashion Design",
    "Architecture",
    "Music",
    "Film Studies",
  ],
  "Business & Finance": [
    "Entrepreneurship",
    "Marketing",
    "Finance",
    "Investing",
    "Leadership",
    "Management",
    "Startups",
    "Economics (Applied)",
  ],
  "Children & Young Adult": [
    "Picture Books",
    "Early Readers",
    "Middle Grade",
    "Young Adult",
    "Fairy Tales",
    "Coming of Age",
    "Children’s Fantasy",
  ],
  Fiction: [
    "Fantasy",
    "Romance",
    "Mystery",
    "Thriller",
    "Horror",
    "Adventure",
    "Crime",
    "Suspense",
    "Spiritual",
    "Poetry",
    "Dystopian",
    "Contemporary",
    "Classic",
    "Literary",
    "Psychological",
    "Philosophical",
    "Sc-fi",
    "Historical",
    "Political",
    "Drama",
    "Young Adult",
    "Gothic",
    "Coming-of-Age",
  ],
  "Health & Lifestyle": [
    "Mental Health",
    "Fitness",
    "Nutrition",
    "Yoga",
    "Meditation",
    "Wellness",
    "Diet & Weight Loss",
  ],
  "Non-Fiction": [
    "Biography",
    "Autobiography",
    "Anthropology",
    "Memoir",
    "Self-Help",
    "Philosophy",
    "Psychology",
    "History",
    "Travel Writing",
    "True Crime",
    "Essays",
    "Personal Development",
    "Personal Finance",
    "Business",
    "Spirituality",
    "Cultural Studies",
    "Inspirational",
    "Life Stories",
  ],
  "Politics & Society": [
    "Political Science",
    "Public Policy",
    "International Relations",
    "Sociology",
    "Human Rights",
    "Constitutional Studies",
  ],
  "Religion & Spirituality": [
    "Hinduism",
    "Islam",
    "Christianity",
    "Buddhism",
    "Sikhism",
    "Mythology",
    "Spiritual Philosophy",
  ],
  Technology: [
    "Web Development",
    "Mobile Development",
    "Data Science",
    "Artificial Intelligence",
    "Machine Learning",
    "Cyber Security",
    "Cloud Computing",
    "DevOps",
    "Game Development",
  ],
  "Travel & Geography": [
    "Travel Guides",
    "Adventure Travel",
    "Cultural Studies",
    "Geography",
    "Travel Writing",
  ],
  Other: ["Other"],
};
